#!/usr/bin/env bash
# Generate the CycloneDX SBOM (software bill of materials) into sbom/:
#
#   sbom/portash.cdx.json  the portash binary (only modules linked into it)
#   sbom/README.md         a readable table of the same
#
# Needs go, jq and cyclonedx-gomod (go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@v1.8.0).
# Output is deterministic (no timestamps, serial numbers or Go version) so CI
# can check it is current.
set -euo pipefail
cd "$(dirname "$0")/.."
GOMOD=${CYCLONEDX_GOMOD:-cyclonedx-gomod}
mkdir -p sbom
raw=$(GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "$GOMOD" app -json -licenses -noserial -main cmd/portash -output - 2>/dev/null)
# The app's own version is a pseudo-version of the current commit; replace it
# so the file only changes when dependencies do.
ver=$(jq -r '.metadata.component.version' <<<"$raw")
sed "s/$ver/source/g" <<<"$raw" | jq -S '
  del(.metadata.timestamp, .serialNumber, .metadata.tools)
  | .metadata.component.licenses = [{license: {id: "MIT"}}]
  | .metadata.component.properties |= ((. // []) | map(select(.name != "cdx:gomod:build:env:GOVERSION")))' \
  >sbom/portash.cdx.json

{
  echo "# Dependencies"
  echo
  echo "Generated by \`scripts/sbom.sh\` from [portash.cdx.json](portash.cdx.json) (CycloneDX). Do not edit."
  echo
  echo "portash is MIT licensed and is built only from its own code and the Go"
  echo "standard library (BSD-3-Clause), which is linked into the binary."
  echo
  n=$(jq '[.components[]?] | length' sbom/portash.cdx.json)
  if [ "$n" = 0 ]; then
    echo "Third-party modules: **none**. Keeping it that way is a design rule"
    echo "(see docs/DESIGN.md); CI fails if this file goes stale."
  else
    echo "| Component | Version | License |"
    echo "|---|---|---|"
    jq -r '.components[] | "| \(.name) | \(.version // "-") | \([(.licenses // .evidence.licenses // [])[] | .license | (.id // .name)] | join(", ") | if . == "" then "unknown" else . end) |"' sbom/portash.cdx.json | sort
  fi
  echo
  echo "Release binaries also embed their build information; \`go version -m portash\`"
  echo "shows the exact Go version and settings a given binary was built with."
} >sbom/README.md
echo "SBOM written to sbom/"
